services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: prana-ai
    environment:
      - ${PORT}=${PORT}
    container_name: prana-ai
    volumes:
      - /home/ubuntu/enquiry/data:/app/data/
      - /home/ubuntu/enquiry/sent_emails:/app/sent_emails/
    ports:
      - "${PORT}:3000"